services:
  examen2:
    image: mysql:8.4.0
    container_name: examen2
    restart: always
    environment:
      # MYSQL_USER: ${DB_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - ${DB_PORT}:${DB_PORT}
